version: '3.9'

services:
  nginx:
    build:
      dockerfile: ./nginx/nginx.Dockerfile
      args:
        WP_USER: user
    environment:
      WP_PATH: "http://wordpress:80/"
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - /upload:/opt/html/upload
    networks:
      - net

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_USER: test_user
      WORDPRESS_DB_PASSWORD: test_password
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', "http://localhost/wp");
        define('WP_HOME', "http://localhost/wp");
        $$_SERVER['REQUEST_URI'] = str_replace("/wp-admin/", "/wp/wp-admin/",  $$_SERVER['REQUEST_URI']);
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - net

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: wp_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - net

networks:
  net:
    driver: bridge